FROM apache/airflow:2.10.0

# Switch to root to install Java (required by Spark client)
USER root
RUN apt-get update && \
    apt-get install -y default-jre-headless && \
    apt-get clean

# Switch back to the airflow user
USER airflow

# Copy requirements file into the container
COPY src/airflow/requirements.txt /requirements.txt

# Install dependencies using the official constraints to prevent command collisions
RUN pip install --no-cache-dir -r /requirements.txt \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.0/constraints-3.12.txt"