FROM python:3.11-slim

WORKDIR /app

COPY src/elastic/requirements.txt ./
COPY src/logger.py ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src/elastic/ ./

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


ENTRYPOINT ["python", "write_network_logs_to_elastic.py"]
